### ISSUE TITLE
`CannotEstimateGas` error when sending Circles to an organization

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#179]
**Describe the bug**

I receive an `CannotEstimateGas` error from the relayer when sending Circles from `0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC` to `0x7B2e78D4dFaABA045A167a70dA285E30E8FcA196`

**Additional context**

Relayer request:

`POST` to `https://relay.circles.garden/api/v2/safes/0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC/transactions/estimate/`

```json
{"safe":"0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC","data":"0xd62fd9a20000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000260000000000000000000000000000000000000000000000000000000000000000400000000000000000000000042cedde51198d1773590311e2a340dc06b24cb370000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac00000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e100000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e100000000000000000000000000000000000000000000000000000000000000040000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac0000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac00000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e1000000000000000000000000000000000000000000000000000000000000000400000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e100000000000000000000000042cedde51198d1773590311e2a340dc06b24cb370000000000000000000000007b2e78d4dfaaba045a167a70da285e30e8fca1960000000000000000000000007b2e78d4dfaaba045a167a70da285e30e8fca196000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000af6e20000000000000000000000000000000000000000000000000de0b6b3a759091e0000000000000000000000000000000000000000000000000de0b6b3a759091e00000000000000000000000000000000000000000000000000000000000af6e2","to":"0x29b9a7fBb8995b2423a71cC17cf9810798F6C543","value":0,"operation":0,"gasToken":"0x0000000000000000000000000000000000000000"}
```

Relayer response:

```
CannotEstimateGas: Received 0x for tx={'value': 0, 'chainId': 100, 'from': '0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC', 'gas': 0, 'gasPrice': 0, 'to': '0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC', 'data': '0xc4ca3a9c00000000000000000000000029b9a7fbb8995b2423a71cc17cf9810798f6c5430000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000304d62fd9a20000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000260000000000000000000000000000000000000000000000000000000000000000400000000000000000000000042cedde51198d1773590311e2a340dc06b24cb370000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac00000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e100000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e100000000000000000000000000000000000000000000000000000000000000040000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac0000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac00000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e1000000000000000000000000000000000000000000000000000000000000000400000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e100000000000000000000000042cedde51198d1773590311e2a340dc06b24cb370000000000000000000000007b2e78d4dfaaba045a167a70da285e30e8fca1960000000000000000000000007b2e78d4dfaaba045a167a70da285e30e8fca196000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000af6e20000000000000000000000000000000000000000000000000de0b6b3a759091e0000000000000000000000000000000000000000000000000de0b6b3a759091e00000000000000000000000000000000000000000000000000000000000af6e200000000000000000000000000000000000000000000000000000000'}
```

Suggested path by `circles-api` service:

```json
{"status":"ok","data":{"from":"0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC","to":"0x7B2e78D4dFaABA045A167a70dA285E30E8FcA196","maxFlowValue":"1000000000000000000","processDuration":6911,"transferValue":"1000000000000000000","transferSteps":[{"from":"0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC","step":0,"to":"0x57928Fb15ffB7303b65EDC326dc4dc38150008e1","value":"718562","tokenOwnerAddress":"0x42cEDde51198D1773590311E2A340DC06B24cB37"},{"from":"0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC","step":1,"to":"0x42cEDde51198D1773590311E2A340DC06B24cB37","value":"999999999999281438","tokenOwnerAddress":"0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC"},{"from":"0x42cEDde51198D1773590311E2A340DC06B24cB37","step":2,"to":"0x7B2e78D4dFaABA045A167a70dA285E30E8FcA196","value":"999999999999281438","tokenOwnerAddress":"0x57928Fb15ffB7303b65EDC326dc4dc38150008e1"},{"from":"0x57928Fb15ffB7303b65EDC326dc4dc38150008e1","step":3,"to":"0x7B2e78D4dFaABA045A167a70dA285E30E8FcA196","value":"718562","tokenOwnerAddress":"0x57928Fb15ffB7303b65EDC326dc4dc38150008e1"}]}}
```

**Comment by adzialocha** [comment]
Trying to estimate the transaction directly via `gnosis-py`:

```python
from gnosis.eth import EthereumClient
from gnosis.safe import Safe

ETHEREUM_NODE_URL = 

ethereum_client = EthereumClient(ETHEREUM_NODE_URL)
safe = Safe('0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC', ethereum_client)
to = '0x29b9a7fBb8995b2423a71cC17cf9810798F6C543'
data = '0xd62fd9a20000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000260000000000000000000000000000000000000000000000000000000000000000400000000000000000000000042cedde51198d1773590311e2a340dc06b24cb370000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac00000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e100000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e100000000000000000000000000000000000000000000000000000000000000040000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac0000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac00000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e1000000000000000000000000000000000000000000000000000000000000000400000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e100000000000000000000000042cedde51198d1773590311e2a340dc06b24cb370000000000000000000000007b2e78d4dfaaba045a167a70da285e30e8fca1960000000000000000000000007b2e78d4dfaaba045a167a70da285e30e8fca196000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000af6e20000000000000000000000000000000000000000000000000de0b6b3a759091e0000000000000000000000000000000000000000000000000de0b6b3a759091e00000000000000000000000000000000000000000000000000000000000af6e2'
result = safe.estimate_tx_gas(to, 0, data, 0)
print(result)
```

Throws this error:

```
execution reverted
Traceback (most recent call last):
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 436, in estimate_tx_gas_with_safe
    result: HexBytes = self.w3.eth.call(tx, block_identifier=block_identifier)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/manager.py", line 157, in request_blocking
    apply_error_formatters(error_formatters, response)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/manager.py", line 62, in apply_error_formatters
    formatted_response = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 514, in raise_solidity_error_on_revert
    raise ContractLogicError('execution reverted')
web3.exceptions.ContractLogicError: execution reverted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    result = safe.estimate_tx_gas(to, 0, data, 0)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 522, in estimate_tx_gas
    return self.estimate_tx_gas_by_trying(to, value, data, operation) + PROXY_GAS + OLD_CALL_GAS
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 491, in estimate_tx_gas_by_trying
    gas_estimated = self.estimate_tx_gas_with_safe(to, value, data, operation)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 449, in estimate_tx_gas_with_safe
    data_dict = error_dict.get('data')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by adzialocha** [comment]
I've ran this test script https://github.com/CirclesUBI/circles-toolbelt/blob/master/test-transfer.js against the steps:

```
CHECK TRANSFER WITH 4 STEPS
0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC -> 0x57928Fb15ffB7303b65EDC326dc4dc38150008e1 OK
0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC -> 0x42cEDde51198D1773590311E2A340DC06B24cB37 OK
0x42cEDde51198D1773590311E2A340DC06B24cB37 -> 0x7B2e78D4dFaABA045A167a70dA285E30E8FcA196 ERROR
   Attempted amount:   999999999999281438
   Actual max. amount: 999997999998420739
0x57928Fb15ffB7303b65EDC326dc4dc38150008e1 -> 0x7B2e78D4dFaABA045A167a70dA285E30E8FcA196 OK
```

**Comment by adzialocha** [comment]
The transaction succeeded with amended parameters (which also were returned by `circles-api` after some time):

```json
[
  {
    "from": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC",
    "step": 0,
    "to": "0x57928Fb15ffB7303b65EDC326dc4dc38150008e1",
    "value": "2000001579261",
    "tokenOwnerAddress": "0x42cEDde51198D1773590311E2A340DC06B24cB37"
  },
  {
    "from": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC",
    "step": 1,
    "to": "0x42cEDde51198D1773590311E2A340DC06B24cB37",
    "value": "999997999998420739",
    "tokenOwnerAddress": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC"
  },
  {
    "from": "0x42cEDde51198D1773590311E2A340DC06B24cB37",
    "step": 2,
    "to": "0x7B2e78D4dFaABA045A167a70dA285E30E8FcA196",
    "value": "999997999998420739",
    "tokenOwnerAddress": "0x57928Fb15ffB7303b65EDC326dc4dc38150008e1"
  },
  {
    "from": "0x57928Fb15ffB7303b65EDC326dc4dc38150008e1",
    "step": 3,
    "to": "0x7B2e78D4dFaABA045A167a70dA285E30E8FcA196",
    "value": "2000001579261",
    "tokenOwnerAddress": "0x57928Fb15ffB7303b65EDC326dc4dc38150008e1"
  }
]
```
