### ISSUE TITLE
npm install deprecated dependencies bug with scrypt

### ISSUE THREAD

**Issue by samuelandert** [CirclesUBI/circles-myxogastria#37]
I just tried to install the circles app locally, but run into an dependency issue with scrypt.

I am using node v12.16.2 and npm v6.14.4

```
../src/node-boilerplate/scrypt_params_async.cc:32:13: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  callback->Call(2, argv);
            ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
8 warnings and 7 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/samuelandert/Documents/dev/circles-baby-phoenix/node_modules/scrypt
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN truffle-hdwallet-provider@0.0.7-beta.1 requires a peer of truffle@4.x but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by adzialocha** [comment]
@samuelandert The last time I tried to build the app with Node v12 I ran into a similar issue, have you tried building it in v11?

**Comment by samuelandert** [comment]
thank you very much, that did the trick.

**Comment by adzialocha** [comment]
Added a comment here: https://github.com/CirclesUBI/circles-baby-phoenix/commit/3280d1cff4cfd563436060ffc6529fca1704254a
