### ISSUE TITLE
Sending CRC fails if MaxAmount cannot be calculated

### ISSUE THREAD

**Issue by houndbee** [CirclesUBI/circles-myxogastria#474]
CRC transactions fail with the following errors, this was working after the fix #457 was deployed, reverting that commit doesn't solve the issue, so it's presumably a backend issue.

````
/send/0xe8A2ba67A6a64F228d143877e2e2431828fF360A?a=1&n=Another%20Test:1 Access to fetch at 'https://api.circles.garden/api/transfers/' from origin 'https://circles.garden' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.js:81622          POST https://api.circles.garden/api/transfers/ net::ERR_FAILED 504
(anonymous) @ index.js:81622
u @ index.js:70206
(anonymous) @ index.js:70347
(anonymous) @ index.js:70239
j @ index.js:70658
o @ index.js:70677
(anonymous) @ index.js:70682
(anonymous) @ index.js:70674
Ya @ index.js:81576
(anonymous) @ index.js:82303
u @ index.js:70206
(anonymous) @ index.js:70347
(anonymous) @ index.js:70239
j @ index.js:70658
o @ index.js:70677
(anonymous) @ index.js:70682
(anonymous) @ index.js:70674
(anonymous) @ index.js:82316
(anonymous) @ index.js:71790
u @ index.js:70206
(anonymous) @ index.js:70347
(anonymous) @ index.js:70239
j @ index.js:70658
o @ index.js:70677
(anonymous) @ index.js:70682
(anonymous) @ index.js:70674
re @ index.js:71768
(anonymous) @ index.js:72066
u @ index.js:70206
(anonymous) @ index.js:70347
(anonymous) @ index.js:70239
j @ index.js:70658
o @ index.js:70677
(anonymous) @ index.js:70682
(anonymous) @ index.js:70674
(anonymous) @ index.js:72077
(anonymous) @ core.js:17
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
We @ app-4a59.js:1
(anonymous) @ core.js:183
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ core.js:182
(anonymous) @ findPath.js:14
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ findPath.js:11
(anonymous) @ SendConfirm.js:191
Rc @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Ic @ react-dom.production.min.js:261
mc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Wi @ react-dom.production.min.js:123
Vi @ react-dom.production.min.js:122
Pe @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
i @ helpers.js:74
Show 47 more frames
/send/0xe8A2ba67A6a64F228d143877e2e2431828fF360A?a=1&n=Another%20Test:1 Access to fetch at 'https://api.circles.garden/api/transfers/' from origin 'https://circles.garden' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.js:81622          POST https://api.circles.garden/api/transfers/ net::ERR_FAILED 504
(anonymous) @ index.js:81622
u @ index.js:70206
(anonymous) @ index.js:70347
(anonymous) @ index.js:70239
j @ index.js:70658
o @ index.js:70677
(anonymous) @ index.js:70682
(anonymous) @ index.js:70674
Ya @ index.js:81576
(anonymous) @ index.js:82303
u @ index.js:70206
(anonymous) @ index.js:70347
(anonymous) @ index.js:70239
j @ index.js:70658
o @ index.js:70677
(anonymous) @ index.js:70682
(anonymous) @ index.js:70674
(anonymous) @ index.js:82316
(anonymous) @ index.js:71790
u @ index.js:70206
(anonymous) @ index.js:70347
(anonymous) @ index.js:70239
j @ index.js:70658
o @ index.js:70677
(anonymous) @ index.js:70682
(anonymous) @ index.js:70674
re @ index.js:71768
(anonymous) @ index.js:72127
u @ index.js:70206
(anonymous) @ index.js:70347
(anonymous) @ index.js:70239
j @ index.js:70658
o @ index.js:70677
Promise.then (async)
j @ index.js:70667
o @ index.js:70677
(anonymous) @ index.js:70682
(anonymous) @ index.js:70674
(anonymous) @ index.js:72217
(anonymous) @ core.js:17
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
We @ app-4a59.js:1
(anonymous) @ core.js:191
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ core.js:190
(anonymous) @ actions.js:226
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ actions.js:214
(anonymous) @ index.js:16
(anonymous) @ SendConfirm.js:137
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ SendConfirm.js:132
qe @ react-dom.production.min.js:52
Xe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Sn @ react-dom.production.min.js:100
kn @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
je @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
In @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Pe @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
i @ helpers.js:74
Show 61 more frames
debug.js:24 [Error] Failed to fetch..
instrument.js:109 TransferError: Failed to fetch
    at index.js:71805:21
    at u (index.js:70206:21)
    at Generator._invoke (index.js:70347:26)
    at Generator.throw (index.js:70239:25)
    at j (index.js:70658:22)
    at s (index.js:70680:11)
(anonymous) @ instrument.js:109
Oo @ debug.js:25
(anonymous) @ SendConfirm.js:151
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ SendConfirm.js:132
qe @ react-dom.production.min.js:52
Xe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Sn @ react-dom.production.min.js:100
kn @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
je @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
In @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Pe @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
i @ helpers.js:74
debug.js:33 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at Oo (debug.js:33:35)
    at SendConfirm.js:151:7
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.throw (runtime.js:118:21)
    at r (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:29:9)
Oo @ debug.js:33
(anonymous) @ SendConfirm.js:151
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ SendConfirm.js:132
qe @ react-dom.production.min.js:52
Xe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Sn @ react-dom.production.min.js:100
kn @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
je @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
In @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Pe @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
i @ helpers.js:74
````

**Comment by llunaCreixent** [comment]
@mikozet , @louilinn , is this still an issue?

**Comment by mikozet** [comment]
It has been fixed
